---
- name: Update all packages to the latest version [Archlinux]
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == 'Archlinux'

- name: Install some special packages - only for Archlinux
  become: yes
  pacman:
    name: "{{ arch_packages }}"
    state: present
  when: ansible_distribution == 'Archlinux'
