---
- name: Update all packages to the latest version [Debian]
  become: yes
  apt:
    upgrade: dist
  when: ansible_os_family == 'Debian'

- name: Update all packages to the latest version [Debian]
  become: yes
  apt:
    name: "{{ debian_packages }}"
    state: latest
  when: ansible_os_family == 'Debian'

