---

- name: print ansible Distribution
  debug:
    msg: 
      - "Distribution: {{ ansible_distribution }}"
      - "OS Family: {{ ansible_os_family }}"

- name: Include OS specific task
  include_task: "{{ ansible_os_family }}.yml"

- name: Install common base office packages
  become: yes
  package:
    name: "{{ generic_office_packages }}"
    state: latest

- name: Install some terminal needs
  become: yes
  package:
    name: "{{ generic_shell_packages }}"
    state: latest

