---

- name: install the latest version of Apache
  dnf:
    name: "{{ rpmfusion }}"
    state: latest
  when: 
    - ansible_distribution == 'Fedora'


- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  when: 
    - ansible_distribution == 'Fedora'

- name: Install common base office packages 
  package:
    name: "{{ office_packages }}"
    state: latest

- name: Install some terminal needs 
  package:
    name: "{{ shell_packages }}"
    state: latest

- name: Install packages for virtualisation
  package:
    name: "{{ virtualisation }}"
    state: latest


