---
- name: print ansible Distribution
  debug:
    msg: 
      - "Distribution: {{ ansible_distribution }}"
      - "OS Family: {{ ansible_os_family }}"
- name: include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS specific task
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install common base office packages
  become: yes
  package:
    name: "{{ generic_office_packages }}"
    state: latest

- name: Install some terminal needs
  become: yes
  package:
    name: "{{ generic_shell_packages }}"
    state: latest

- name: Include and enable printer support
  become: true
  include_tasks: "printer.yml"
  when: install_cups 
