---

- name: Install cups for printing
  become: true
  package:
    name: "{{ printer_packages }}"
    state: present

- name: Install arch packages
  become: true
  pacman:
    name: "{{ arch_printer_packages }}"
    state: present
  when: ansible_os_family == 'Archlinux'
  
- name: Enable and start cups
  become: true
  systemd:
    name: org.cups.cupsd.service
    state: started
    enabled: yes

- name: Enable and start avahi for printer detection in local area network
  become: true
  systemd:
    name: avahi-daemon.service
    state: started
    enabled: yes
  when: ansible_os_family == 'Archlinux'

